{-# OPTIONS --cubical --safe --guardedness #-}
--
-- THE COFINALITY — every rational below φ is below some running convergent  (Item A, converse).
--
-- The Dedekind cut of φ is GENERATED by the running corridor: cut-to-runs says q ∈ φL ⟹ ∃n, q < lo n.
-- With the landed DedekindBridge.lo<φ (∃n, q<lo n ⟹ q ∈ φL) this makes φL q ⟺ ∃n, q < lo n — the two
-- φ's (the Dedekind point and the running corridor) have the SAME cut.  Engine: the Cassini gap
-- 1/D² (GapBound) → 0 (recip→0, via Forcing's unbounded denominators + ℚ-archimedean), so f(lo n) =
-- 1 − 1/D² climbs past f(q) for any q below φ, and quad-squeeze reflects that to q < lo n.
--
module corpus.cubical_agda.Corridor.Running.General.Cofinal where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ; suc; zero) renaming (_·_ to _·ℕ_; _+_ to _+ℕ_)
open import Cubical.Data.Nat.Order using (≤-trans; suc-≤-suc) renaming (_≤_ to _≤ℕ_)
open import Cubical.Data.NatPlusOne using (ℕ₊₁; 1+_; _·₊₁_; ℕ₊₁→ℕ)
open import Cubical.Data.Int using (ℤ; pos) renaming (_·_ to _·ℤ_; ·IdL to ·IdLℤ)
open import Cubical.Data.Int.Order using () renaming (_≤_ to _≤ℤ_; _<_ to _<ℤ_)
open import Cubical.Data.Sigma using (Σ-syntax; _,_)
open import Cubical.HITs.PropositionalTruncation as PT using (∥_∥₁)
open import Cubical.Data.Rationals
open import Cubical.Data.Rationals.Order using (_<_; _≤_; isTrans≤<)
open import corpus.cubical_agda.Corridor.Running.Bracket using (fibP; dbl)
open import corpus.cubical_agda.Corridor.Running.Forcing using (fpN; fpN-lower; fpN-pos; le-mult; M≤dbl)
open import corpus.cubical_agda.Corridor.Running.LocatedLaw using (n→ℕ·₊₁)
open import corpus.cubical_agda.Corridor.Running.General.Archimedean using (ℚ-archimedean)
open import corpus.cubical_agda.Corridor.Running.General.GeometricBoundQ using (posMono)

-- the Cassini gap 1/D² is driven below any ε > 0.
recip→0 : (ε : ℚ) → 0 < ε
        → ∥ Σ[ n ∈ ℕ ] ([ pos 1 / (fibP (dbl n) ·₊₁ fibP (dbl n)) ] < ε) ∥₁
recip→0 ε 0<ε = PT.map step (ℚ-archimedean ε 0<ε)
  where
    step : Σ[ m ∈ ℕ ] ([ pos 1 / 1+ m ] < ε)
         → Σ[ n ∈ ℕ ] ([ pos 1 / (fibP (dbl n) ·₊₁ fibP (dbl n)) ] < ε)
    step (m , h) = suc m ,
      isTrans≤< [ pos 1 / (D ·₊₁ D) ] [ pos 1 / 1+ m ] ε recip-le h
      where
        D : ℕ₊₁
        D = fibP (dbl (suc m))
        X : ℕ
        X = ℕ₊₁→ℕ D                                  -- = fpN (dbl (suc m))
        sucm≤X : suc m ≤ℕ X
        sucm≤X = ≤-trans (suc-≤-suc (≤-trans (M≤dbl m) (1 , refl)))
                         (fpN-lower (suc (dbl m)))   -- suc(suc(dbl m)) ≤ fpN(suc(suc(dbl m))) = X
        sucm≤XX : suc m ≤ℕ ℕ₊₁→ℕ (D ·₊₁ D)
        sucm≤XX = subst (suc m ≤ℕ_) (sym (n→ℕ·₊₁ D D))
                    (≤-trans sucm≤X (le-mult X X (fpN-pos (dbl (suc m)))))
        recip-le : [ pos 1 / (D ·₊₁ D) ] ≤ [ pos 1 / 1+ m ]
        recip-le = subst2 _≤ℤ_ (sym (·IdLℤ (ℕ₊₁→ℤ (1+ m))))
                               (sym (·IdLℤ (ℕ₊₁→ℤ (D ·₊₁ D))))
                               (posMono sucm≤XX)
