{-# OPTIONS --cubical --safe --guardedness #-}
--
-- THE COFINALITY — every rational below φ is below some running convergent  (Item A, converse).
--
-- The Dedekind cut of φ is GENERATED by the running corridor: cut-to-runs says q ∈ φL ⟹ ∃n, q < lo n.
-- With the landed DedekindBridge.lo<φ (∃n, q<lo n ⟹ q ∈ φL) this makes φL q ⟺ ∃n, q < lo n — the two
-- φ's (the Dedekind point and the running corridor) have the SAME cut.  Engine: the Cassini gap 1/D²
-- (GapBound) → 0 (recip→0, via Forcing's unbounded denominators + ℚ-archimedean), so f(lo n) = lo n²−
-- lo n = 1 − 1/D² climbs past f(q) for any q below φ, and quad-squeeze (the order-reflection through
-- f(x)=x²−x) turns that into q < lo n.  No new analysis — the corridor IS the point.
--
module corpus.cubical_agda.Corridor.Running.General.Cofinal where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Structure using (⟨_⟩)
open import Cubical.Data.Nat using (ℕ; suc; zero) renaming (_·_ to _·ℕ_; _+_ to _+ℕ_)
open import Cubical.Data.Nat.Order using (≤-trans; suc-≤-suc; zero-≤) renaming (_≤_ to _≤ℕ_)
open import Cubical.Data.NatPlusOne using (ℕ₊₁; 1+_; _·₊₁_; ℕ₊₁→ℕ)
open import Cubical.Data.Int using (ℤ; pos) renaming (_·_ to _·ℤ_; ·IdL to ·IdLℤ)
open import Cubical.Data.Int.Order using () renaming (_≤_ to _≤ℤ_; _<_ to _<ℤ_)
open import Cubical.Data.Sigma using (Σ-syntax; _,_; _×_)
open import Cubical.Data.Sum using (_⊎_; inl; inr)
open import Cubical.Relation.Nullary using (yes; no)
open import Cubical.HITs.PropositionalTruncation as PT using (∥_∥₁; ∣_∣₁; squash₁)
open import Cubical.Algebra.CommRing using (CommRing; CommRingStr)
open import Cubical.Algebra.CommRing.Instances.Rationals using (ℚCommRing)
open import Cubical.Tactics.CommRingSolver using (solve!)

-- abstract ring rearrangements (solve! cannot run on the concrete ℚ SetQuotient; BEFORE the ℚ open
-- so the ring ops do not clash).
module _ (R : CommRing ℓ-zero) where
  open CommRingStr (snd R)
  r1 : (xx x d : ⟨ R ⟩) → (xx + (- x)) ≡ (((xx + d) + (- d)) + (- x))
  r1 xx x d = solve! R
  r2 : (x d : ⟨ R ⟩) → (((x + 1r) + (- d)) + (- x)) ≡ (1r + (- d))
  r2 x d = solve! R
  r3 : (q qq : ⟨ R ⟩) → (((q + 1r) + (- qq)) + (qq + (- q))) ≡ 1r
  r3 q qq = solve! R
  r4 : (q qq d : ⟨ R ⟩) → (((d + (qq + (- q))) + (- d))) ≡ (qq + (- q))
  r4 q qq d = solve! R
  -- the f(x)=x²−x factorisation (forward order step):  f(r) − f(q) = (r−q)(r+q−1).
  r5 : (q r : ⟨ R ⟩)
     → (((r · r) + (- r)) + (- ((q · q) + (- q)))) ≡ ((r + (- q)) · ((r + q) + (- 1r)))
  r5 q r = solve! R
  r6 : (x : ⟨ R ⟩) → ((x + 1r) + (- x)) ≡ 1r
  r6 x = solve! R
  r7 : (q qq : ⟨ R ⟩) → ((qq + (- q)) + q) ≡ qq
  r7 q qq = solve! R

open import Cubical.Data.Rationals
open import Cubical.Data.Rationals.Order
  using (_<_; _≤_; isTrans<; isTrans<≤; isTrans≤<; <-+o; <-o+; <-·o; ≮→≥; <Dec)
open import corpus.cubical_agda.RealCohesion.DedekindReal using (0<1ℚ)
open import corpus.cubical_agda.RealCohesion.GoldenCut using (φL; small-quad)
open import corpus.cubical_agda.RealCohesion.DedekindReal using (⟦_⟧)
open import corpus.cubical_agda.Corridor.Running.Bracket using (fibP; dbl; lo)
open import corpus.cubical_agda.Corridor.Running.Forcing using (fpN; fpN-lower; fpN-pos; le-mult; M≤dbl)
open import corpus.cubical_agda.Corridor.Running.LocatedLaw
  using (n→ℕ·₊₁; loPlus1; loPlus1≡; oneℚ; golden-lower-faithful)
open import corpus.cubical_agda.Corridor.Running.CrossCut using (lo-mono)
open import corpus.cubical_agda.Corridor.Running.General.Archimedean using (ℚ-archimedean)
open import corpus.cubical_agda.Corridor.Running.General.GeometricBoundQ using (posMono)
open import corpus.cubical_agda.Corridor.Running.General.GapBound using (gapForm)
open import corpus.cubical_agda.Corridor.Running.General.QuadSqueeze using (quad-squeeze)

oneℚ≡1 : oneℚ ≡ 1
oneℚ≡1 = refl

-- the Cassini gap 1/D² is driven below any ε > 0.
recip→0 : (ε : ℚ) → 0 < ε
        → ∥ Σ[ n ∈ ℕ ] ([ pos 1 / (fibP (dbl n) ·₊₁ fibP (dbl n)) ] < ε) ∥₁
recip→0 ε 0<ε = PT.map step (ℚ-archimedean ε 0<ε)
  where
    step : Σ[ m ∈ ℕ ] ([ pos 1 / 1+ m ] < ε)
         → Σ[ n ∈ ℕ ] ([ pos 1 / (fibP (dbl n) ·₊₁ fibP (dbl n)) ] < ε)
    step (m , h) = suc m ,
      isTrans≤< [ pos 1 / (D ·₊₁ D) ] [ pos 1 / 1+ m ] ε recip-le h
      where
        D : ℕ₊₁
        D = fibP (dbl (suc m))
        X : ℕ
        X = ℕ₊₁→ℕ D
        sucm≤X : suc m ≤ℕ X
        sucm≤X = ≤-trans (suc-≤-suc (≤-trans (M≤dbl m) (1 , refl)))
                         (fpN-lower (suc (dbl m)))
        sucm≤XX : suc m ≤ℕ ℕ₊₁→ℕ (D ·₊₁ D)
        sucm≤XX = subst (suc m ≤ℕ_) (sym (n→ℕ·₊₁ D D))
                    (≤-trans sucm≤X (le-mult X X (fpN-pos (dbl (suc m)))))
        recip-le : [ pos 1 / (D ·₊₁ D) ] ≤ [ pos 1 / 1+ m ]
        recip-le = subst2 _≤ℤ_ (sym (·IdLℤ (ℕ₊₁→ℤ (1+ m))))
                               (sym (·IdLℤ (ℕ₊₁→ℤ (D ·₊₁ D))))
                               (posMono sucm≤XX)

-- THE COFINALITY:  q below φ ⟹ q below some running convergent.
cut-to-runs : (q : ℚ) → ⟦ φL ⟧ q → ∥ Σ[ n ∈ ℕ ] (q < lo n) ∥₁
cut-to-runs q = PT.rec squash₁ branch
  where
    -- q < lo 0  (= 1) for any q below 1.
    below1 : (q : ℚ) → q < 1 → Σ[ n ∈ ℕ ] (q < lo n)
    below1 q q<1 = 0 , q<1

    -- 0 < lo n  (lo n ≥ lo 0 = 1 > 0).
    0<lon : (n : ℕ) → 0 < lo n
    0<lon n = isTrans<≤ 0 1 (lo n) 0<1ℚ (lo-mono 0 n zero-≤)

    branch : (q < 0) ⊎ ((q · q) < (q + 1)) → ∥ Σ[ n ∈ ℕ ] (q < lo n) ∥₁
    branch (inl q<0) = ∣ below1 q (isTrans< q 0 1 q<0 0<1ℚ) ∣₁
    branch (inr qsq) with <Dec q 1
    ... | yes q<1 = ∣ below1 q q<1 ∣₁
    ... | no ¬q<1 = PT.map use (recip→0 gapq 0<gapq)
      where
        1≤q : 1 ≤ q
        1≤q = ≮→≥ q 1 ¬q<1
        gapq : ℚ
        gapq = (q + 1) + (- (q · q))
        0<gapq : 0 < gapq
        0<gapq = subst (_< gapq) (+InvR (q · q))
                   (<-+o (q · q) (q + 1) (- (q · q)) qsq)
        use : Σ[ n ∈ ℕ ] ([ pos 1 / (fibP (dbl n) ·₊₁ fibP (dbl n)) ] < gapq)
            → Σ[ n ∈ ℕ ] (q < lo n)
        use (n , hn) = n , quad-squeeze q (lo n) qlt 1<q+lon
          where
            d : ℚ
            d = [ pos 1 / (fibP (dbl n) ·₊₁ fibP (dbl n)) ]
            h1 : (lo n + 1) ≡ ((lo n · lo n) + d)
            h1 = subst (λ z → (lo n + z) ≡ ((lo n · lo n) + d)) oneℚ≡1
                   (sym (loPlus1≡ n) ∙ gapForm n)
            floEq : ((lo n · lo n) + (- lo n)) ≡ (1 + (- d))
            floEq = r1 ℚCommRing (lo n · lo n) (lo n) d
                  ∙ cong (λ z → (z + (- d)) + (- lo n)) (sym h1)
                  ∙ r2 ℚCommRing (lo n) d
            s1 : (d + ((q · q) + (- q))) < gapq + ((q · q) + (- q))
            s1 = <-+o d gapq ((q · q) + (- q)) hn
            s1' : (d + ((q · q) + (- q))) < 1
            s1' = subst ((d + ((q · q) + (- q))) <_) (r3 ℚCommRing q (q · q)) s1
            s2 : ((d + ((q · q) + (- q))) + (- d)) < (1 + (- d))
            s2 = <-+o (d + ((q · q) + (- q))) 1 (- d) s1'
            s2' : ((q · q) + (- q)) < (1 + (- d))
            s2' = subst (_< (1 + (- d))) (r4 ℚCommRing q (q · q) d) s2
            qlt : ((q · q) + (- q)) < ((lo n · lo n) + (- lo n))
            qlt = subst (((q · q) + (- q)) <_) (sym floEq) s2'
            1<q+lon : 1 < (q + lo n)
            1<q+lon = isTrans≤< 1 q (q + lo n) 1≤q
                        (subst (_< (q + lo n)) (+IdR q) (<-o+ 0 (lo n) q (0<lon n)))

-- forward order step:  q < r and 1 < q+r  ⟹  f(q) < f(r)   (f x = x²−x increasing on (½,∞)).
quad-mono : (q r : ℚ) → q < r → 1 < (q + r)
          → ((q · q) + (- q)) < ((r · r) + (- r))
quad-mono q r q<r 1<qr = 0<sub→<
  where
    0<r-q : 0 < (r + (- q))
    0<r-q = subst (_< (r + (- q))) (+InvR q) (<-+o q r (- q) q<r)
    0<r+q-1 : 0 < ((r + q) + (- 1))
    0<r+q-1 = subst (_< ((r + q) + (- 1))) (+InvR 1)
                (<-+o 1 (r + q) (- 1) (subst (1 <_) (+Comm q r) 1<qr))
    0<prod : 0 < ((r + (- q)) · ((r + q) + (- 1)))
    0<prod = subst (_< ((r + (- q)) · ((r + q) + (- 1)))) (·AnnihilL ((r + q) + (- 1)))
               (<-·o 0 (r + (- q)) ((r + q) + (- 1)) 0<r+q-1 0<r-q)
    0<diff : 0 < (((r · r) + (- r)) + (- ((q · q) + (- q))))
    0<diff = subst (0 <_) (sym (r5 ℚCommRing q r)) 0<prod
    0<sub→< : ((q · q) + (- q)) < ((r · r) + (- r))
    0<sub→< = subst2 _<_ (+IdL ((q · q) + (- q)))
                (sym (+Assoc ((r · r) + (- r)) (- ((q · q) + (- q))) ((q · q) + (- q)))
                  ∙ cong (((r · r) + (- r)) +_) (+InvL ((q · q) + (- q))) ∙ +IdR ((r · r) + (- r)))
                (<-+o 0 (((r · r) + (- r)) + (- ((q · q) + (- q)))) ((q · q) + (- q)) 0<diff)

-- THE CONVERSE BRIDGE:  q below some convergent ⟹ q ∈ φL  (q below φ).
runs→cut : (q : ℚ) → ∥ Σ[ n ∈ ℕ ] (q < lo n) ∥₁ → ⟦ φL ⟧ q
runs→cut q = PT.rec squash₁ wit
  where
    wit : Σ[ n ∈ ℕ ] (q < lo n) → ⟦ φL ⟧ q
    wit (n , q<lon) with <Dec q 0
    ... | yes q<0 = ∣ inl q<0 ∣₁
    ... | no ¬q<0 with <Dec q 1
    ...   | yes q<1 = ∣ inr (small-quad q (≮→≥ q 0 ¬q<0) q<1) ∣₁
    ...   | no ¬q<1 = ∣ inr qsq ∣₁
      where
        0<lon-n : 0 < lo n
        0<lon-n = isTrans<≤ 0 1 (lo n) 0<1ℚ (lo-mono 0 n zero-≤)
        1<q+lon : 1 < (q + lo n)
        1<q+lon = isTrans≤< 1 q (q + lo n) (≮→≥ q 1 ¬q<1)
                    (subst (_< (q + lo n)) (+IdR q) (<-o+ 0 (lo n) q 0<lon-n))
        flon<1 : ((lo n · lo n) + (- lo n)) < 1
        flon<1 = subst (((lo n · lo n) + (- lo n)) <_) (r6 ℚCommRing (lo n))
                   (<-+o (lo n · lo n) (lo n + 1) (- lo n) (golden-lower-faithful n))
        fq<1 : ((q · q) + (- q)) < 1
        fq<1 = isTrans< ((q · q) + (- q)) ((lo n · lo n) + (- lo n)) 1
                 (quad-mono q (lo n) q<lon 1<q+lon) flon<1
        qsq : (q · q) < (q + 1)
        qsq = subst2 _<_ (r7 ℚCommRing q (q · q)) (+Comm 1 q)
                (<-+o ((q · q) + (- q)) 1 q fq<1)

-- ════════════════════════════════════════════════════════════════════════════
-- RUNNING ≅ DEDEKIND φ — the two φ's have the SAME cut: φL q ⟺ ∃n, q < lo n.
-- ════════════════════════════════════════════════════════════════════════════
running≅dedekind : (q : ℚ)
                 → (⟦ φL ⟧ q → ∥ Σ[ n ∈ ℕ ] (q < lo n) ∥₁)
                 × (∥ Σ[ n ∈ ℕ ] (q < lo n) ∥₁ → ⟦ φL ⟧ q)
running≅dedekind q = cut-to-runs q , runs→cut q
